server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: dolphin-compose
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://110.42.60.129:10002/postgres?currentSchema=public&TimeZone=UTC
        username: postgres
        password: postgres
    jackson:
        time-zone: Asia/Shanghai
        date-format: yyyy-MM-dd HH:mm:ss
